baseURL = 'https://til.andrew-quinn.me/'
languageCode = 'en-us'
title = "Andrew Quinn's TILs"
theme = 'PaperMod'

enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true

[minify]
disableXML = true

[languages.en]
languageName = "English"
weight = 1

  [languages.en.taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

  [[languages.en.menu.main]]
  name = "Archive"
  url = "https://github.com/hiAndrewQuinn/til"
  weight = 100

  [[languages.en.menu.main]]
  name = "Search"
  url = "https://github.com/search?q=repo%3AhiAndrewQuinn%2Ftil+&type=code"
  weight = 200

  [[languages.en.menu.main]]
  name = "Tags"
  url = "tags/"
  weight = 300

  [[languages.en.menu.main]]
  name = "andrew-quinn.me"
  url = "https://andrew-quinn.me"
  weight = 400


[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
defaultTheme = "auto"
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
images = [ "papermod-cover.png" ]

  [params.profileMode]
  enabled = false
  title = "PaperMod"
  imageUrl = "#"
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Archives"
    url = "archives"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Andrew Quinn's TILs"
  Content = """
A place to keep track of things I've learned. Inspired by [Simon Willison's TILs](https://til.simonwillison.net).

All thoughts, opinions, etc. expressed herein are strictly my own and not of my employer's.

Consulting available under the business name [Siilikuin](https://siilikuin.com). For inquiries please email my first name at siilikuin.com.

**Comments at the bottom of every page**, including this one - check it out!
  """

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/hiAndrewQuinn/til"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/heiandrewquinn"

  [[params.socialIcons]]
  name = "x"
  url = "https://x.com/hiAndrewQuinn"

  [[params.socialIcons]]
  name = "Rss"
  url = "index.xml"

  [params.assets]
  disableHLJS = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = true
codeFences = true
guessSyntax = true
lineNos = true
style = "monokai"

[privacy.vimeo]
disabled = true
simple = true

[privacy.x]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = true
simple = true

[privacy.youtube]
disabled = true
privacyEnhanced = true

[services.instagram]
disableInlineCSS = true

[services.x]
disableInlineCSS = true
